[project]
name = "render-box-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyside6>=6.7.2",
]


[tool.uv]
dev-dependencies = [
    "mypy>=1.11.1",
    "pyside6-stubs>=6.4.2.0",
    "ruff>=0.6.1",
]
